apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: knrt10/kubernetes
        ports:
        - containerPort: 8080
